name: AutoRelease
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: debug
        run: |
          echo "the tag: $TAG"
          echo "token: ${{ secrets.GITHUB_TOKEN }}"
      - name: create release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token 
          gh auth status
          gh release create $TAG --generate-notes
