name: AutoRelease
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: debug
        run: |
          echo "the tag: $TAG"
      - name: create release
        run: |
          gh release create $TAG --generate-notes
          

